services:
  - type: web
    name: cyber-savvy-frontend
    env: static
    buildCommand: |
      npm install
      npm run build:render
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 